function gameObject() {
  return {
    home: {
      teamName: 'Brooklyn Nets',
      colors: ['Black', 'White'],
      players: [
        {
          playerName: 'Alan Anderson',
          number: 0,
          shoe: 16,
          points: 22,
          rebounds: 12,
          assists: 12,
          steals: 3,
          blocks: 1,
          slumDunks: 1,
        },
        {
          playerName: 'Reggoe Evans',
          number: 30,
          shoe: 14,
          point: 12,
          rebounds: 12,
          assists: 12,
          steals: 12,
          blocks: 12,
          slumDunks: 7,
        },
        {
          playerName: 'Brook Lopez',
          numer: 11,
          shoe: 17,
          point: 17,
          rebounds: 19,
          assists: 10,
          steals: 3,
          blocks: 1,
          slumDunks: 15,
        },
        {
          playerName: 'Mason Plumlee',
          number: 1,
          shoe: 19,
          point: 26,
          rebounds: 12,
          assists: 6,
          steals: 3,
          blocks: 8,
          slumDunks: 5,
        },
        {
          playerName: 'Jason Terry',
          number: 31,
          shoe: 15,
          point: 19,
          rebounds: 2,
          assists: 2,
          steals: 4,
          blocks: 11,
          slumDunks: 1,
        },
      ],
    },
    away: {
      teamName: 'Charlotte Hornets',
      colors: ['Turquoise', 'Purple'],
      players: [
        {
          playerName: 'Jeff Afrien',
          number: 4,
          shoe: 18,
          point: 10,
          rebounds: 1,
          assists: 1,
          steals: 2,
          blocks: 7,
          slumDunks: 2,
        },
        {
          playerName: 'Bismak Biyombo',
          number: 0,
          shoe: 16,
          point: 12,
          rebounds: 4,
          assists: 7,
          steals: 7,
          blocks: 15,
          slumDunks: 10,
        },
        {
          playerName: 'DeSagna Diop',
          number: 2,
          shoe: 14,
          point: 24,
          rebounds: 12,
          assists: 12,
          steals: 4,
          blocks: 5,
          slumDunks: 5,
        },
        {
          playerName: 'Ben Gordon',
          number: 8,
          shoe: 15,
          point: 33,
          rebounds: 3,
          assists: 2,
          steals: 1,
          blocks: 1,
          slumDunks: 0,
        },
        {
          playerName: 'Brendan Haywood',
          number: 33,
          shoe: 15,
          point: 6,
          rebounds: 12,
          assists: 12,
          steals: 22,
          blocks: 5,
          slumDunks: 12,
        },
      ],
    },
  }
}

console.log(gameObject())
